apiVersion: v1
data:
  branch: demo-mq-v2-sherryyyu
  host: github.com
  org: sherryyyu
  owner: sherryyyu
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops
  url: https://github.com/sherryyyu/multi-tenancy-gitops.git
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
  namespace: ci
